'use strict';


const fakeUserInput = {
    name: 'fakuser',
    password: 'fakepasss'
};



const sampleUserDisabled = {
    username: 'disuser',
    email: 'some@example.com',
    password: 'somepass'
};

const sampleUser = {
    username: 'properuser',
    email: 'sampleuser@example.com',
    password: 'properpassword',
    enabled: true
};
const validUserInput = {
    name: 'properuser',
    password: 'properpassword'
};

const sampleUser2 = {
    username: 'anotherproperuser',
    email: 'anothersampleuser@example.com',
    password: 'properpassword',
    enabled: true
};
const validUserInput2 = {
    name: 'anotherproperuser',
    password: 'properpassword'
};


const newIDPConfInput = {
    "@context": "http://geant.org/capusidp/context",
    "@type": "ServiceDescription",
    "components": {
        "@type": "Collection",
        "web": {
            "@type": "WebServer",
            "software": {},
            "hostname": "idp.example.com",
            "http": {
                "port": 80
            },
            "https": {
                "port": 443,
                "publicKey": {
                    "@type": "X509Certificate",
                    "@value": "xxxxxxx"
                },
                "privateKey": {
                    "@type": "autoGenerated"
                }
            }
        },
        "idp": {
            "@type": "IdPConf",
            "entityID": {
                "@type": "autoGenerated"
            },
            "software": {
                "name": "shibboleth-idp",
                "version": "3.1.3"
            },
            "metadataProviders": [
                {
                    "@type": "MetadataProvider",
                    "attrID": "edugate",
                    "url": "https://edugate.heanet.ie/example-signed-meta.xml",
                    "publicKey": {
                        "@type": "X509Certificate",
                        "@value": "XYZ"
                    }
                }
            ],
            "sso": {
              "@type" : "autoGenerated"
            },
            "aa": {
                "certificates": []
            }
        }
    }
};
const newIDPConfInput2 = {
    "@context": "http://geant.org/capusidp/context",
    "@type": "ServiceDescription",
    "components": {
        "@type": "Collection",
        "web": {
            "@type": "WebServer",
            "software": {},
            "hostname": "idp2.example.com",
            "http": {
                "port": 80
            },
            "https": {
                "port": 443,
                "publicKey": {
                    "@type": "X509Certificate",
                    "@value": "xxxxxxx"
                },
                "privateKey": {
                    "@type": "autoGenerated"
                }
            }
        },
        "idp": {
            "@type": "IdPConf",
            "entityID": {
                "@type" : "autoGenerated"
            },
            "software": {
                "name": "shibboleth-idp",
                "version": "3.1.3"
            },
            "metadataProviders": [
                {
                    "@type": "MetadataProvider",
                    "attrID": "edugate",
                    "url": "https://edugate.heanet.ie/example-signed-meta.xml",
                    "publicKey": {
                        "@type": "X509Certificate",
                        "@value": "XYZ"
                    }
                }
            ],
            "sso": {
                "certificates": []
            },
            "aa": {
                "certificates": []
            }
        }
    }


};



const invalidIDPConfInput_1 = {
    "@context": "http://geant.org/capusidp/context",
    "@type": "InvalidDescription",
    "components": {
        "@type": "Collection",
        "web": {
            "@type": "WebServer",
            "software": {},
            "hostname": "idp.example.com",
            "http": {
                "port": 80
            },
            "https": {
                "port": 443,
                "publicKey": {
                    "@type": "X509Certificate",
                    "@value": "xxxxxxx"
                },
                "privateKey": {
                    "@type": "autoGenerated"
                }
            }
        },
        "idp": {
            "@type": "IdPConf",
            "entityID": "https://idp.example.com/idp",
            "software": {
                "name": "shibboleth-idp",
                "version": "3.1.3"
            },
            "metadataProviders": [
                {
                    "@type": "MetadataProvider",
                    "attrID": "edugate",
                    "url": "https://edugate.heanet.ie/example-signed-meta.xml",
                    "publicKey": {
                        "@type": "X509Certificate",
                        "@value": "XYZ"
                    }
                }
            ],
            "sso": {
                "@type" : "autoGenerated"
            },
            "aa": {
                "@type" : "autoGenerated"
            }
        }
    }


};
// missing hostname
const invalidIDPConfInput_2 = {
    "@context": "http://geant.org/capusidp/context",
    "@type": "ServiceDescription",
    "components": {
        "@type": "Collection",
        "web": {
            "@type": "WebServer",
            "software": {},
            "http": {
                "port": 80
            },
            "https": {
                "port": 443,
                "publicKey": {
                    "@type": "X509Certificate",
                    "@value": "xxxxxxx"
                },
                "privateKey": {
                    "@type": "autoGenerated"
                }
            }
        },
        "idp": {
            "@type": "IdPConf",
            "entityID": "https://idp.example.com/idp",
            "software": {
                "name": "shibboleth-idp",
                "version": "3.1.3"
            },
            "metadataProviders": [
                {
                    "@type": "MetadataProvider",
                    "attrID": "edugate",
                    "url": "https://edugate.heanet.ie/example-signed-meta.xml",
                    "publicKey": {
                        "@type": "X509Certificate",
                        "@value": "XYZ"
                    }
                }
            ],
            "sso": {
                "certificates": []
            },
            "aa": {
                "certificates": []
            }
        }
    }


};
module.exports.invalidIDPConfInput_1 = invalidIDPConfInput_1;
module.exports.invalidIDPConfInput_2 = invalidIDPConfInput_2;
module.exports.fakeUserInput = fakeUserInput;
module.exports.sampleUser = sampleUser;
module.exports.sampleUser2 = sampleUser2;
module.exports.sampleDisabledUser = sampleUserDisabled;
module.exports.validUserInput = validUserInput;
module.exports.validUserInput2 = validUserInput2;
module.exports.newIDPConfInput = newIDPConfInput;
module.exports.newIDPConfInput2 = newIDPConfInput2;