
const vocab = "http://geant.org/schema/campusidp/";

var context = {
    "@vocab": vocab,
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "ref": {
        "@type": "@id"
    },
    "confRef": {
        "@type": "@id"
    },
    "dependency": {
        "@type": "@id"
    },
    "exposed": {
        "@type": "xsd:boolean"
    },
    "apiVersion": "xsd:string"
};

var schema = {
    "@context": {
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "xsd": "http://www.w3.org/2001/XMLSchema#"
    },
    "@graph" : [
        {
            "@id" : vocab+"autoGenerated",
            "@type": "rdfs:Class",
            "rdfs:comment": "If any property points to a node of this class then api server is signaled to generate value for the property.",
            "rdfs:label": "autoGenerated"
        },
        {
            "@id" : vocab+"ServiceDescription",
            "@type": "rdfs:Class",
            "rdfs:comment": "The main node Service configuration.",
            "rdfs:label": "ServiceDescription"
        },
        {
            "@id" : vocab+"WebServer",
            "@type": "rdfs:Class",
            "rdfs:comment": "WebServer frontend configuration.",
            "rdfs:label": "WebServer"
        },
        {
            "@id" : vocab+"IdPConf",
            "@type": "rdfs:Class",
            "rdfs:comment": "Identity Provider configuration.",
            "rdfs:label": "Identity Provider configuration"
        },
        {
            "@id" : vocab+"AttributeDefinition",
            "@type": "rdfs:Class",
            "rdfs:comment": "Definition of an attribute ex. attribute-resolver.",
            "rdfs:label": "Definition of an attribute"
        },
        {
            "@id" : vocab+"DataSource",
            "@type": "rdfs:Class",
            "rdfs:comment": "Definition of data source",
            "rdfs:label": "Definition of data source"
        },
        {
            "@id" : vocab+"MetadataProvider",
            "@type": "rdfs:Class",
            "rdfs:comment": "MetadataProvider definition",
            "rdfs:label": "MetadataProvider definition"
        },
        {
            "@id" : vocab+"hostname",
            "@type": "rdf:Property",
            "http://schema.org/domainIncludes" : [
                {
                    "@id" : vocab+"WebServer"
                }
            ],
            "rdfs:comment": "Hostname.",
            "rdfs:label": "hostname"
        },
        {
            "@id" : vocab+"http",
            "@type": "rdf:Property",
            "http://schema.org/domainIncludes" : [
                {
                    "@id" : vocab+"WebServer"
                }
            ],
            "rdfs:comment": "http",
            "rdfs:label": "http"
        },
        {
            "@id" : vocab+"https",
            "@type": "rdf:Property",
            "http://schema.org/domainIncludes" : [
                {
                    "@id" : vocab+"WebServer"
                }
            ],
            "rdfs:comment": "https",
            "rdfs:label": "https"
        },
        {
            "@id" : vocab+"port",
            "@type": "rdf:Property",
            "rdfs:comment": "http(s) port",
            "rdfs:label": "http(s) port"
        },
        {
            "@id" : vocab+"privateKey",
            "@type": "rdf:Property",
            "rdfs:comment": "private Key",
            "rdfs:label": "private Key"
        },
        {
            "@id" : vocab+"privateKeyPassword",
            "@type": "rdf:Property",
            "rdfs:comment": "private Key Password",
            "rdfs:label": "private Key Password"
        },
        {
            "@id" : vocab+"publicKey",
            "@type": "rdf:Property",
            "rdfs:comment": "public Certificate",
            "rdfs:label": "public Certificate"
        },
        {
            "@id" : vocab+"software",
            "@type": "rdf:Property",
            "http://schema.org/domainIncludes" : [
                {
                    "@id" : vocab+"IdPConf"
                },
                {
                    "@id" : vocab+"WebServer"
                }
            ],
            "rdfs:comment": "information about software used by component",
            "rdfs:label": "information about software used by component"
        },
        {
            "@id" : vocab+"name",
            "@type": "rdf:Property",
            "rdfs:comment": "Name property. Can be used by any node",
            "rdfs:label": "name"
        },
        {
            "@id" : vocab+"version",
            "@type": "rdf:Property",
            "rdfs:comment": "version",
            "rdfs:label": "version"
        },
        {
            "@id" : vocab+"entityID",
            "@type": "rdf:Property",
            "http://schema.org/domainIncludes" : [
                {
                    "@id" : vocab+"IdPConf"
                }
            ],
            "rdfs:comment": "entityID of Identity/Service Provider",
            "rdfs:label": "entityID of Identity/Service Provider"
        },
        {
            "@id" : vocab+"metadataProviders",
            "@type": "rdf:Property",
            "http://schema.org/domainIncludes" : [
                {
                    "@id" : vocab+"IdPConf"
                }
            ],
            "rdfs:comment": "collection of metadataProviders",
            "rdfs:label": "collection of metadataProviders"
        },
        {
            "@id" : vocab+"idpsso",
            "@type": "rdf:Property",
            "http://schema.org/domainIncludes" : [
                {
                    "@id" : vocab+"IdPConf"
                }
            ],
            "rdfs:comment": "idpsso",
            "rdfs:label": "idpsso"
        },
        {
            "@id" : vocab+"aa",
            "@type": "rdf:Property",
            "http://schema.org/domainIncludes" : [
                {
                    "@id" : vocab+"IdPConf"
                }
            ],
            "rdfs:comment": "aa",
            "rdfs:label": "aa"
        }

    ]
}


module.exports.context = context;
module.exports.schema = schema;